version: '3'
services:
  postgres:
    container_name: task-management
    build: .
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
